default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: me3ll_photography
  username: my_bow
  password: myAxe!

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  #password: <%= ENV['me3ll_photography_DATABASE_PASSWORD'] %>